name: Generate Snake Animation

on:
  # Ejecutar autom치ticamente cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permitir ejecuci칩n manual desde la pesta침a Actions
  workflow_dispatch:
  
  # Ejecutar en cada push a main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Genera la animaci칩n de la serpiente
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: GMSantiago-Dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-light.svg?palette=github-light
      
      # Sube los archivos generados a la rama output
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
